---
language: java

jdk:
- oraclejdk8

before_install:
  - ls -lthra
  - java -version

install:
  - mvn install
  # - mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs # spotbugs goal produces a report target/spotbugsXml.xml
  - mvn com.github.spotbugs:spotbugs-maven-plugin:check # check goal produces a report and produces build failed if bugs
  # the spotbugsXml.xml file is easiest read in a web browser
  # see http://spotbugs.readthedocs.io/en/latest/maven.html and https://spotbugs.github.io/spotbugs-maven-plugin/index.html for more info

script:
  - mvn cobertura:cobertura # for codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  emails: false
